title: Tinkering with Genode
description: Episodes of professional and leisure-time hacking
show_downloads: false
author: Christian Helmuth

baseurl:
url: "https://chelmuth.github.io"
github:
  is_project_page: false

google_analytics:
# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

plugins:
    - jekyll-feed
    - jekyll-sitemap
    - jekyll-mentions
    - jekyll-seo-tag

